### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.msvccompiler' in aur

### ISSUE THREAD

**Issue by littleblack111** [wmww/gtk4-layer-shell#46] opened 2024-09-06 15:16 UTC
when installing by aur, log:
```
AUR Explicit (1): gtk4-layer-shell-1.0.2-4
:: PKGBUILD up to date, skipping download: gtk4-layer-shell
  1 gtk4-layer-shell                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 gtk4-layer-shell                 (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: gtk4-layer-shell 1.0.2-4 (Fri 06 Sep 2024 11:15:37 PM HKT)
==> Retrieving sources...
  -> Found gtk4-layer-shell-1.0.2.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    gtk4-layer-shell-1.0.2.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: gtk4-layer-shell
==> Making package: gtk4-layer-shell 1.0.2-4 (Fri 06 Sep 2024 11:15:38 PM HKT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found gtk4-layer-shell-1.0.2.tar.gz
==> Validating source files with sha256sums...
    gtk4-layer-shell-1.0.2.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting gtk4-layer-shell-1.0.2.tar.gz with bsdtar
==> Sources are ready.
==> Making package: gtk4-layer-shell 1.0.2-4 (Fri 06 Sep 2024 11:15:40 PM HKT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
The Meson build system
Version: 1.5.1
Source dir: /home/system/.cache/yay/gtk4-layer-shell/src/gtk4-layer-shell-1.0.2
Build dir: /home/system/.cache/yay/gtk4-layer-shell/src/build
Build type: native build
Project name: gtk4-layer-shell
Project version: 1.0.2
C compiler for the host machine: ccache cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240805")
C linker for the host machine: cc ld.bfd 2.43.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency gtk4 found: YES 4.14.5
Run-time dependency wayland-client found: YES 1.23.0
Run-time dependency wayland-server found: YES 1.23.0
Build-time dependency wayland-scanner found: YES 1.23.0
Run-time dependency wayland-protocols found: YES 1.37
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Run-time dependency gobject-introspection-1.0 found: YES 1.80.1
Dependency gobject-introspection-1.0 found: YES 1.80.1 (cached)
Program /usr/bin/g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.80.1 (cached)
Program /usr/bin/g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Program vapigen found: YES (/usr/bin/vapigen)
Vala compiler for the host machine: valac (valac 0.56.17)
Configuring gtkdocentities.ent using configuration
Run-time dependency glib-2.0 found: YES 2.80.5
Program gtkdoc-scan found: YES (/usr/bin/gtkdoc-scan)
Program gtkdoc-scangobj found: YES (/usr/bin/gtkdoc-scangobj)
Program gtkdoc-mkdb found: YES (/usr/bin/gtkdoc-mkdb)
Program gtkdoc-mkhtml found: YES (/usr/bin/gtkdoc-mkhtml)
Program gtkdoc-fixxref found: YES (/usr/bin/gtkdoc-fixxref)
Program sh found: YES (/usr/bin/sh)
Build targets in project: 9
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.build_root', 'meson.source_root'}

gtk4-layer-shell 1.0.2

  User defined options
    buildtype    : plain
    prefix       : /usr
    wrap_mode    : nofallback
    docs         : true
    examples     : false
    introspection: true
    smoke-tests  : false
    tests        : false
    vapi         : true

Found ninja-1.12.1 at /usr/bin/ninja
ninja: Entering directory `build'
[13/18] Generating src/Gtk4LayerShell-1.0.gir with a custom command (wrapped by meson to set env)
FAILED: src/Gtk4LayerShell-1.0.gir
env PKG_CONFIG_PATH=/home/system/.cache/yay/gtk4-layer-shell/src/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config 'CC=ccache cc' /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=Gtk4LayerShell --nsversion=1.0 --warn-all --output src/Gtk4LayerShell-1.0.gir --c-include=gtk4-layer-shell.h -I/home/system/.cache/yay/gtk4-layer-shell/src/gtk4-layer-shell-1.0.2/src -I/home/system/.cache/yay/gtk4-layer-shell/src/build/src -I/home/system/.cache/yay/gtk4-layer-shell/src/gtk4-layer-shell-1.0.2/include/. -I/home/system/.cache/yay/gtk4-layer-shell/src/build/include/. --filelist=/home/system/.cache/yay/gtk4-layer-shell/src/build/src/libgtk4-layer-shell.so.1.0.2.p/Gtk4LayerShell_1.0_gir_filelist --include=Gtk-4.0 --symbol-prefix=gtk_layer --identifier-prefix=GtkLayerShell --pkg-export=gtk4-layer-shell-0 --cflags-begin -I/home/system/.cache/yay/gtk4-layer-shell/src/gtk4-layer-shell-1.0.2/include/. -I/home/system/.cache/yay/gtk4-layer-shell/src/build/include/. -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/sysprof-6 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/system/.cache/yay/gtk4-layer-shell/src/build/src --library gtk4-layer-shell -lgtk-4 -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lvulkan -lgraphene-1.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lwayland-client -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 25, in <module>
    from .ccompiler import CCompiler
  File "/usr/lib/gobject-introspection/giscanner/ccompiler.py", line 29, in <module>
    from distutils.msvccompiler import MSVCCompiler
ModuleNotFoundError: No module named 'distutils.msvccompiler'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gtk4-layer-shell-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
gtk4-layer-shell - exit status 4
```

**Comment by wmww** [comment] 2024-09-10 05:09
Possibly related: https://github.com/pyodide/pyodide/issues/2971, https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed

Not sure where the issue is, but doesn't seem to be something this repo can do anything about (it does not contain the AUR packaging)

**Comment by littleblack111** [comment] 2024-09-12 11:57
i described in https://gitlab.archlinux.org/archlinux/packaging/packages/gobject-introspection/-/issues/2 on how it can be fixed

**Comment by Baldi-OG** [comment] 2024-09-12 13:35
> I encountered a similar issue, probably related to the same cause.
> 
> `yay -S gtk4-layer-shell -> No AUR package found for gtk4-layer-shell there is nothing to do`

A system upgrade seems to have fixed that problem already.

**Comment by wmww** [comment] 2024-10-27 00:01
Maybe related to it being moved from the AUR to the main Arch repos? Closing, will reopen if this continues to be a problem.

**Closed by wmww** 2024-10-27 00:01 UTC
